xanmel_web/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'', include('map_rating.urls', namespace='map_rating')),
    url(r'xdf/', include('xdf.urls', namespace='xdf')),
    url(r'sorm/', include('sorm.urls', namespace='sorm')),
    url(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='login.jinja'), name='login'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),

]

xdf/urls.py
from django.conf.urls import *

from .views import *


app_name = 'xdf'

urlpatterns = [
    url('^$', IndexView.as_view(), name='index'),
    url('^servers/$', ServerListView.as_view(), name='servers'),
    url('^maps/$', MapListView.as_view(), name='maps'),
    url('^maps/(.*)/$', MapView.as_view(), name='map'),
    url('^players/$', ClassicLadderView.as_view(), name='classic-ladder'),
    url(r'^players/(\d+)/$', PlayerView.as_view(), name='player'),
    url(r'^players/(\d+)/activity/$', PlayerActivityView.as_view(), name='player-activity'),
    url(r'^players/(\d+)/speed-records/$', PlayerSpeedRecordsView.as_view(), name='player-speed-records'),
    url(r'^players/(\d+)/time-records/$', PlayerTimeRecordsView.as_view(), name='player-time-records'),
    url(r'^players/compare/$', CompareView.as_view(), name='compare'),
    url(r'^players/search/$', AdvancedPlayerSearchView.as_view(), name='player-search')

]

xdf/forms.py
from django import forms
from django.utils.safestring import mark_safe

from xanmel.modules.xonotic.models import *


class NewsFeedFilterForm(forms.Form):
    event_types = forms.MultipleChoiceField(choices=EventType.choices(),
                                            initial=[i.value for i in EventType],
                                            widget=forms.CheckboxSelectMultiple(),
                                            required=False)
    maps = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'map name matches'}),
                           required=False)
    players = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'player name matches'}),
                              required=False)
    position_lte = forms.IntegerField(required=False,
                                      widget=forms.NumberInput(attrs={'placeholder': 'position <='}))

    def __init__(self, *args, **kwargs):
        servers = list(XDFServer.select(XDFServer.id, XDFServer.name))
        server_ids = [i.id for i in servers]
        kwargs['data'] = kwargs['data'].copy()
        if 'event_types' not in kwargs['data']:
            for i in EventType:
                kwargs['data'].update(event_types=i.value)
        if 'servers' not in kwargs['data']:
            for i in server_ids:
                kwargs['data'].update(servers=i)
        super().__init__(*args, **kwargs)
        self.fields['servers'] = forms.MultipleChoiceField(
            choices=[(i.id, i.name) for i in servers],
            initial=server_ids,
            widget=forms.CheckboxSelectMultiple(),
            required=False)


class MapListOrder(EChoice):
    MAP_NAME_ASC = (0, mark_safe('Map Name &uarr;'))
    MAP_NAME_DESC = (1, mark_safe('Map Name &darr;'))
    PLAYER_ASC = (3, mark_safe('Record Holder &uarr;'))
    PLAYER_DESC = (4, mark_safe('Record Holder &darr;'))
    TIME_ASC = (5, mark_safe('Time &uarr;'))
    TIME_DESC = (6, mark_safe('Time &darr;'))
    TOP_SPEED_PLAYER_ASC = (7, mark_safe('Top Speed Holder &uarr;'))
    TOP_SPEED_PLAYER_DESC = (8, mark_safe('Top Speed Holder &darr;'))
    TOP_SPEED_ASC = (9, mark_safe('Top Speed &uarr;'))
    TOP_SPEED_DESC = (10, mark_safe('Top Speed &darr;'))


class MapListFilterForm(forms.Form):
    maps = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'map name matches'}),
                           required=False)

    def __init__(self, *args, **kwargs):
        servers = list(XDFServer.select(XDFServer.id, XDFServer.name))
        server_ids = [i.id for i in servers]
        if  'servers' not in kwargs['data']:
            kwargs['data'] = kwargs['data'].copy()
            for i in server_ids:
                kwargs['data'].update(servers=i)
        super().__init__(*args, **kwargs)

        self.fields['servers'] = forms.MultipleChoiceField(
            choices=[(i.id, i.name) for i in servers],
            initial=server_ids,
            widget=forms.CheckboxSelectMultiple(),
            required=False)


class MapFilterForm(forms.Form):
    def __init__(self, *args, **kwargs):
        servers = list(XDFServer.select(XDFServer.id, XDFServer.name))
        server_ids = [i.id for i in servers]
        if 'servers' not in kwargs['data']:
            kwargs['data'] = kwargs['data'].copy()
            for i in server_ids:
                kwargs['data'].update(servers=i)
        super().__init__(*args, **kwargs)
        self.fields['servers'] = forms.MultipleChoiceField(
            choices=[(i.id, i.name) for i in servers],
            initial=server_ids,
            widget=forms.CheckboxSelectMultiple(),
            required=False)


class LadderFilterForm(forms.Form):
    players = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'player name matches'}),
                              required=False)
    ladder_type = forms.ChoiceField(choices=LadderType.choices(), required=False)

    def __init__(self, *args, **kwargs):
        servers = list(XDFServer.select(XDFServer.id, XDFServer.name))
        super().__init__(*args, **kwargs)
        self.fields['server'] = forms.ChoiceField(choices=[(i.id, i.name) for i in servers], required=False)


class PlayerRecordSearchForm(MapListFilterForm):
    position_gte = forms.IntegerField(widget=forms.NumberInput(attrs={'placeholder': 'position >='}),
                                      required=False)
    position_lte = forms.IntegerField(widget=forms.NumberInput(attrs={'placeholder': 'position <='}),
                                      required=False)


class CompareWithForm(forms.Form):
    player1 = forms.IntegerField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        players = XDFPlayer.select().order_by(XDFPlayer.nickname)
        self.fields['player2'] = forms.ChoiceField(choices=[(i.id, i.nickname) for i in players])


class SearchType(EChoice):
    CRYPTO_IDFP = ('crypto_idfp', 'Crypto IDFP')
    STATS_ID = ('stats_id', 'Xonstats ID')
    NICKNAME = ('nickname', 'Nickname')


class SearchPlayerForm(forms.Form):
    query = forms.CharField()
    query_type = forms.ChoiceField(choices=SearchType.choices())

xdf/views.py
import urllib.parse
from collections import OrderedDict

from django.http import Http404, HttpResponseBadRequest
from django.shortcuts import render
from django.conf import settings
from django.urls import reverse
from django.views import View
from peewee import fn

from xanmel.modules.xonotic.models import *
from xdf.templatetags.xdf import format_time

from .forms import NewsFeedFilterForm, MapListFilterForm, MapFilterForm, LadderFilterForm, CompareWithForm, \
    SearchPlayerForm, SearchType, PlayerRecordSearchForm
from .utils import paginate_query


def format_player_with_link(player):
    return '<a href="{}">{}</a>'.format(
        reverse('xdf:player', args=(player.id,)),
        player.nickname
    )


class HelpersMixin:
    @staticmethod
    def format_news_item(news_item):
        if news_item.event_type == EventType.SPEED_RECORD.value:
            return "{} set high speed record &mdash; {}qu/s".format(
                format_player_with_link(news_item.speed_record.player),
                round(news_item.speed_record.speed)
            )
        elif news_item.event_type == EventType.TIME_RECORD.value:
            if news_item.time_record.video_url:
                yt_link = '<a target="_blank" href="{}">{}s <i class="fab fa-youtube"></i></a>'.format(
                    news_item.time_record.video_url,
                    format_time(news_item.time_record.time),
                )
            else:
                yt_link = '{}s'.format(format_time(news_item.time_record.time), )
            return "{} set time &mdash; {} (server {}/{}, global {}/{})".format(
                format_player_with_link(news_item.time_record.player),
                yt_link,
                news_item.time_record.server_pos,
                news_item.time_record.server_max_pos,
                news_item.time_record.global_pos,
                news_item.time_record.global_max_pos,
            )

    @staticmethod
    def count_rest(data):
        res = 0
        for i in range(11, 101):
            res += data.get(str(i), 0)
        return res


class IndexView(View, HelpersMixin):

    def get(self, request):
        form = NewsFeedFilterForm(data=request.GET)
        if not form.is_valid():
            raise Http404
        p1 = XDFPlayer.alias()
        p2 = XDFPlayer.alias()
        news = (XDFNewsFeed.select()
                .join(XDFTimeRecord, JOIN_LEFT_OUTER, on=(XDFNewsFeed.time_record == XDFTimeRecord.id))
                .join(p1, JOIN_LEFT_OUTER, on=(XDFTimeRecord.player == p1.id))
                .join(XDFSpeedRecord, JOIN_LEFT_OUTER, on=(XDFNewsFeed.speed_record == XDFSpeedRecord.id))
                .join(p2, JOIN_LEFT_OUTER, on=(XDFSpeedRecord.player == p2.id))
                .order_by(XDFNewsFeed.timestamp.desc()))
        if form.cleaned_data['maps']:
            pattern = '%{}%'.format(form.cleaned_data['maps'])
            news = news.where(XDFTimeRecord.map ** pattern | XDFSpeedRecord.map ** pattern)
        if form.cleaned_data['players']:
            pattern = '%{}%'.format(form.cleaned_data['players'])
            news = news.where(p1.nickname ** pattern | p2.nickname ** pattern)
        servers = form.cleaned_data['servers']
        news = news.where(XDFTimeRecord.server.in_(servers) | XDFSpeedRecord.server.in_(servers))
        news = news.where(XDFNewsFeed.event_type.in_(form.cleaned_data['event_types']))
        if form.cleaned_data['position_lte']:
            news = news.where(XDFTimeRecord.server_pos <= form.cleaned_data['position_lte'])
        total_news = news.count()
        news = paginate_query(request, news)
        return render(request, 'xdf/index.jinja', {
            'form': form,
            'news': news,
            'total_news': total_news,
            'format_news_item': self.format_news_item,
            'current_nav_tab': 'index'
        })


class ServerListView(View):
    @staticmethod
    def count_maps(server):
        return XDFTimeRecord \
            .select(XDFTimeRecord.map) \
            .where(XDFTimeRecord.server == server) \
            .distinct().count()

    @staticmethod
    def count_players(server):
        return (XDFTimeRecord
                .select(XDFTimeRecord.player)
                .where(XDFTimeRecord.server == server)
                .distinct().count())

    def get(self, request):
        servers = XDFServer.select().order_by(XDFServer.name)
        return render(request, 'xdf/servers.jinja', {
            'servers': servers,
            'current_nav_tab': 'servers',
            'count_maps': self.count_maps,
            'count_players': self.count_players
        })


class MapListView(View):
    def get_speed_record(self, servers, map_name):
        top_speed = 0
        record = None
        q = (XDFSpeedRecord.select(XDFPlayer.nickname.alias('nickname'),
                                   XDFPlayer.id.alias('player_id'),
                                   XDFSpeedRecord.speed.alias('speed'))
             .join(XDFPlayer)
             .where(XDFSpeedRecord.map == map_name))
        if servers:
            q = q.where(XDFSpeedRecord.server.in_(servers))
        for i in q.dicts():
            if i['speed'] > top_speed:
                record = i
                top_speed = i['speed']
        return record

    def get_time_record(self, servers, map_name):
        top_time = None
        record = None
        total_times = 0
        q = (XDFTimeRecord.select(XDFPlayer.nickname.alias('nickname'),
                                  XDFPlayer.id.alias('player_id'),
                                  XDFTimeRecord.time.alias('time'),
                                  XDFTimeRecord.video_url.alias('video_url'))
             .join(XDFPlayer)
             .where(XDFTimeRecord.map == map_name))
        if servers:
            q = q.where(XDFTimeRecord.server.in_(servers))
        for i in q.dicts():
            if top_time is None or i['time'] < top_time:
                top_time = i['time']
                record = i
            total_times += 1
        return total_times, record

    def get(self, request):
        form = MapListFilterForm(data=request.GET)
        if not form.is_valid():
            raise Http404()

        maps = XDFTimeRecord.select(XDFTimeRecord.map).order_by(XDFTimeRecord.map)
        servers = None

        if form.cleaned_data['maps']:
            maps = maps.where(XDFTimeRecord.map ** '%{}%'.format(form.cleaned_data['maps']))
        if form.cleaned_data['servers']:
            servers = form.cleaned_data['servers']
            maps = maps.where(XDFTimeRecord.server.in_(form.cleaned_data['servers']))

        maps = maps.distinct()
        total_maps = maps.count()
        maps = paginate_query(request, maps)
        maps = maps.tuples()

        table = []
        for i in maps:
            map_name = i[0]
            total_times, time_record = self.get_time_record(servers, map_name)
            table.append(
                {'map': map_name,
                 'time_record': time_record,
                 'total_times': total_times,
                 'speed_record': self.get_speed_record(servers, map_name)}
            )

        return render(request, 'xdf/maps.jinja', {
            'current_nav_tab': 'maps',
            'table': table,
            'form': form,
            'total_maps': total_maps
        })


class MapView(View):
    def get(self, request, map_name):
        form = MapFilterForm(data=request.GET)
        if not form.is_valid():
            raise Http404
        map_name = urllib.parse.unquote(map_name)
        servers = form.cleaned_data['servers']
        speed_records = (XDFSpeedRecord.select()
                         .where(XDFSpeedRecord.map == map_name)
                         .where(XDFSpeedRecord.server.in_(servers))
                         .order_by(XDFSpeedRecord.speed.desc()))
        speed_records_dedup = []
        players = set()
        for i in speed_records:
            if i.player not in players:
                speed_records_dedup.append(i)
                players.add(i.player)
        time_records_dedup = []
        players = set()
        time_records = (XDFTimeRecord.select()
                        .where(XDFTimeRecord.map == map_name)
                        .where(XDFTimeRecord.server.in_(servers))
                        .order_by(XDFTimeRecord.time, XDFTimeRecord.server_pos, SQL('video_url DESC NULLS LAST')))
        for i in time_records:
            if i.player not in players:
                time_records_dedup.append(i)
                players.add(i.player)
        return render(request, 'xdf/map.jinja', {
            'current_nav_tab': 'maps',
            'map_name': map_name,
            'speed_records': speed_records_dedup,
            'time_records': time_records_dedup,
            'form': form
        })


class ClassicLadderView(View, HelpersMixin):
    def get(self, request):
        form = LadderFilterForm(data=request.GET)
        form.is_valid()
        t = form.cleaned_data['ladder_type'] and int(form.cleaned_data['ladder_type']) or LadderType.GLOBAL.value
        s = form.cleaned_data['server']
        players = form.cleaned_data['players']

        if t == LadderType.GLOBAL.value:
            try:
                ladder = XDFLadder.get(XDFLadder.algo == LadderAlgo.CLASSIC.value,
                                       XDFLadder.type == LadderType.GLOBAL.value)
            except DoesNotExist:
                raise Http404()
            positions = (XDFLadderPosition.select()

                         .where(XDFLadderPosition.ladder == ladder)
                         .order_by(XDFLadderPosition.position))
        else:
            try:
                ladder = XDFLadder.get(XDFLadder.algo == LadderAlgo.CLASSIC.value,
                                       XDFLadder.type == LadderType.SERVER.value,
                                       XDFLadder.server == s)
            except DoesNotExist:
                raise Http404

xdf/templates/xdf/_favs.jinja
<link rel="apple-touch-icon" sizes="57x57" href="{{ static('img/favs/apple-icon-57x57.png') }}">
<link rel="apple-touch-icon" sizes="60x60" href="{{ static('img/favs/apple-icon-60x60.png') }}">
<link rel="apple-touch-icon" sizes="72x72" href="{{ static('img/favs/apple-icon-72x72.png') }}">
<link rel="apple-touch-icon" sizes="76x76" href="{{ static('img/favs/apple-icon-76x76.png') }}">
<link rel="apple-touch-icon" sizes="114x114" href="{{ static('img/favs/apple-icon-114x114.png') }}">
<link rel="apple-touch-icon" sizes="120x120" href="{{ static('img/favs/apple-icon-120x120.png') }}">
<link rel="apple-touch-icon" sizes="144x144" href="{{ static('img/favs/apple-icon-144x144.png') }}">
<link rel="apple-touch-icon" sizes="152x152" href="{{ static('img/favs/apple-icon-152x152.png') }}">
<link rel="apple-touch-icon" sizes="180x180" href="{{ static('img/favs/apple-icon-180x180.png') }}">
<link rel="icon" type="image/png" sizes="192x192"  href="{{ static('img/favs/android-icon-192x192.png') }}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ static('img/favs/favicon-32x32.png') }}">
<link rel="icon" type="image/png" sizes="96x96" href="{{ static('img/favs/favicon-96x96.png') }}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ static('img/favs/favicon-16x16.png') }}">
<link rel="manifest" href="{{ static('img/favs/manifest.json') }}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{{ static('img/favs/ms-icon-144x144.png') }}">
<meta name="theme-color" content="#ffffff">

xdf/templates/xdf/_pagination.jinja
<div>
  <ul class="pagination">
    <li class="page-item {% if current_page == 1 %}disabled{% endif %}">
      <a class="page-link" href="{% if current_page != 1 %}?{{ prev_link }}{% endif %}">&laquo;</a>
    </li>

    <li class="page-item active">
      <a class="page-link" href="#">Page {{ current_page }} of {{ total_pages }}</a>
    </li>

    <li class="page-item {% if current_page == total_pages %}disabled{% endif %}">
      <a class="page-link" href="{% if current_page != total_pages %}?{{ next_link }}{% endif %}">&raquo;</a>
    </li>
  </ul>
</div>

xdf/templates/xdf/base.jinja
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{{ static('css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ static('css/xdf.css') }}">
    <link rel="stylesheet" href="{{ static('fa/css/fontawesome-all.min.css') }}">
    <title>{% block title %}{% endblock %}</title>
    {% include "xdf/_favs.jinja" %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url('xdf:index') }}">Xonotic DeFRaG</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if current_nav_tab == 'index' %}active{% endif %}">
                <a class="nav-link" href="{{ url('xdf:index') }}">News</a>
            </li>
            <li class="nav-item {% if current_nav_tab == 'servers' %}active{% endif %}">
                <a class="nav-link" href="{{ url('xdf:servers') }}">Servers</a>
            </li>
            <li class="nav-item {% if current_nav_tab == 'maps' %}active{% endif %}">
                <a class="nav-link" href="{{ url('xdf:maps') }}">Maps</a>
            </li>
            <li class="nav-item {% if current_nav_tab == 'players' %}active{% endif %}">
                <a class="nav-link" href="{{ url('xdf:classic-ladder') }}">Players</a>
            </li>

        </ul>

    </div>
</nav>

<div class="container main-container">
    <div class="row">
        {% block content %}
        {% endblock %}
    </div>
    <footer id="footer">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <ul class="list-unstyled">
                            <li class="float-lg-right"><a href="#top">Back to top</a></li>
                            {% if request.user.is_anonymous %}
                                <li><a href="{{ login_url(request) }}">Login</a></li>
                            {% else %}
                                <li><a href="{{ url('logout') }}">Logout</a></li>
                            {% endif %}
                            <li><a href="https://xonotic.org/">Xonotic Website</a></li>
                            <li><a href="https://discord.gg/v447EHx">XDF Discord</a></li>
                            <li><a href="http://webchat.quakenet.org/?channels=#xdf">IRC: quakenet/#xdf</a></li>

                        </ul>
                        <p>Website made by <a href="https://portal.exe.pub/xdf/players/4/">Morosophos</a>,<br>
                            <a href="https://github.com/nsavch/xanmel-web">source code</a> available under GNU AGPL-3.0 license.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>

</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
{% block extra_js %}
{% endblock %}
</html>

xdf/templates/xdf/compare.jinja
{% extends "xdf/base.jinja" %}

{% block title %}{{ player1.nickname }} vs {{ player2.nickname }} - Xonotic DeFRaG{% endblock %}


{% block content %}
    <div class="col-md-12">
        <h1>Xonotic DeFRaG</h1>
        <h2>{{ player1.nickname }} vs {{ player2.nickname }}</h2>
        <ul>
            <li><a href="{{ url('xdf:player', player1.id) }}">{{ player1.nickname }}</a>
                 is better on <strong>{{ summary['p1_better'] }}</strong> maps</li>
            <li><a href="{{ url('xdf:player', player2.id) }}">{{ player2.nickname }}</a>
                is better on <strong>{{ summary['p2_better'] }}</strong> maps</li>
            <li>Total gap is <strong>{{ summary['total_gap']|floatformat(0) }}%</strong></li>
        </ul>
        <table class="table table-bordered table-striped">
            <tr>
                <th>
                    map
                </th>
                <th>
                    {{ player1.nickname }}
                </th>
                <th>
                    {{ player2.nickname }}
                </th>
                <th>

                </th>
            </tr>
            {% for m, p1, mp, t1, p2, t2, gap in results %}
                <tr>
                    <td><a href="{{ url('xdf:map', urlquote(m)) }}">{{ m }}</a></td>
                    <td>#{{ p1 }}/{{ mp }} &mdash; {{ format_time(t1) }}s</td>
                    <td>#{{ p2 }}/{{ mp }} &mdash; {{ format_time(t2) }}s</td>
                    <td style="min-width: 300px">
                        <div class="progress">
                            {% if t1 < t2 %}
                                <div class="progress-bar bg-success" role="progressbar"
                                     style="width: {{ gap | floatformat(0) }}%; min-width: 2em;">
                                    {{ gap|floatformat(0) }}%
                                </div>
                            {% else %}
                                <div class="progress-bar bg-danger" role="progressbar"
                                     style="width: {{ gap | floatformat(0) }}%; min-width: 2em;">
                                    {{ gap|floatformat(0) }}%
                                </div>
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

xdf/templates/xdf/ladder_classic.jinja
{% extends "xdf/base.jinja" %}

{% block title %}Classic Ladder - Xonotic DeFRaG{% endblock %}

{% block content %}
    <div class="col-md-12">
        <h1>Xonotic DeFRaG</h1>
        <h2 class="page-header">Classic Ladder</h2>
        <form class="filter-form">
            <div class="row">
                <div class="col">
                    {{ bootstrap_field(form.players, show_label=False) }}
                </div>

                <div class="col">
                    {{ bootstrap_field(form.ladder_type, show_label=False) }}
                </div>

                <div id="server-col" class="col d-none">
                    {{ bootstrap_field(form.server, show_label=False) }}
                </div>

                <div class="col">
                    <button class="btn btn-primary">refresh</button>
                </div>
            </div>
        </form>
        <p><a href="{{ url('xdf:player-search') }}">Advanced Search</a></p>
        {% if ladder.timestamp %}
            <p>Updated {{ format_timestamp(ladder.timestamp) }}</p>
        {% endif %}
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Player</th>
                <th>Points</th>
                <th>Speed Records</th>
                {% for i in columns %}
                    <th>{{ i }}</th>
                {% endfor %}
                <th>&gt; 10</th>
            </tr>
            </thead>
            <tbody>
            {% for pos in positions %}
                <tr>
                    <td>{{ pos.position }}</td>
                    <td><a href="{{ url('xdf:player', pos.player_id) }}">{{ pos.player.nickname }}</a></td>
                    <td>{{ pos.points|round }}</td>
                    <td>{{ pos.data.get('speed', 0) }}</td>
                    {% for i in columns %}
                        <td>{{ pos.data.get(i, 0) }}</td>
                    {% endfor %}
                    <td>{{ count_rest(pos.data) }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {{ render_pagination(request, total_positions) }}

    </div>

{% endblock %}

{% block extra_js %}
    <script>
        function handleFormChange() {
            var val = $('select#id_ladder_type').val();
            console.log(val);
            if (val === '2') {
                $('#server-col').removeClass('d-none');
            } else {
                $('#server-col').addClass('d-none');
            }

        }
        handleFormChange();
        $('select#id_ladder_type').on('change', handleFormChange);
    </script>
{% endblock %}

xdf/templates/xdf/player_search.jinja
{% extends "xdf/base.jinja" %}

{% block title %}Search Players - Xonotic DeFRaG{% endblock %}


{% block content %}
    <div class="col-md-12">
        <h1>Xonotic DeFRaG</h1>
        <h2>Search Players</h2>
    <form class="mb-5">
        {{ bootstrap_field(form.query, layout='horizontal') }}
        {{ bootstrap_field(form.query_type, layout='horizontal') }}
        <button class="btn btn-primary">Search</button>
    </form>
    {% if searched %}
        <p>Found {{ players|length }} results</p>
        <ul>
        {% for i in players %}
        <li><a href="{{ url('xdf:player', i.id) }}">{{ i.nickname }}</a></li>
        {% endfor %}
        </ul>
    {% endif %}
    </div>
{% endblock %}

xdf/templates/xdf/player_speed_records.jinja
{% extends "xdf/base.jinja" %}

{% block title %}Speed Records of {{ player.nickname }} - Xonotic DeFRaG{% endblock %}


{% block content %}
    <div class="col-md-12">
        <h1>Xonotic DeFRaG</h1>
        <h2>Speed Records of <a href="{{ url('xdf:player', player.id) }}">{{ player.nickname }}</a></h2>
        <p>View <a href="{{ url('xdf:player-time-records', player.id) }}">time records</a></p>
        <div class="row">
            <div class="col-lg-6 col-md-9 col-12">
                <table class="table table-bordered table-striped">
                    {% for i in records.values() %}
                        <tr>
                            <th><a href="{{ url('xdf:map', urlquote(i.map)) }}">{{ i.map }}</a></th>
                            <td>{{ i.speed|round }}qu/s</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>

    </div>
{% endblock %}